### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by Alex293** [devxoul/Pure#3]
Hi, 

Can you provide a minimal example ? 

I don't get how to access dependencies, shouldn't Module have properties for dependencies and payload ? What the point of providing default initializers if dependencies / payload are thrown away ?

**Comment by innocarpe** [comment]
Hi, you can store dependency in the initializer like this if you needed to access the dependency after the initializing. 

```swift
import UIKit

import Pure

final class SomeViewController: UIViewController, FactoryModule {

  // MARK: Module

  struct Dependency {
    ...
  }

  struct Payload {
    ...
  }


  // MARK: Properties

  private let dependency: Dependency


  // MARK: Initializing

  init(dependency: Dependency, payload: Payload) {
    self.dependency = dependency
    super.init()
    // Do initializing
  }

  ...

}
```

I hope this is what you intend. 😃

**Comment by nonameplum** [comment]
Better late than never 😄
https://github.com/devxoul/Pure/pull/15 (example without `Pure` - Lazy Dependency)
https://github.com/devxoul/Pure/pull/14 (example with `Pure`)
